# Generated by Django 6.0.4 on 2026-07-12 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='examenes.curso')),
            ],
            options={
                'db_table': 'objetivos_curso',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='examen',
            name='objetivos',
            field=models.ManyToManyField(blank=True, help_text='Objetivos del curso que este examen evalúa. Si hay, la IA ancla cada pregunta a uno de ellos', related_name='examenes', to='examenes.objetivocurso'),
        ),
    ]
