# Generated by Django 6.0.4 on 2026-07-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_objetivocurso_examen_objetivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, help_text='Fecha límite para INICIAR un intento nuevo. Vacío = sin límite. No afecta un intento ya en progreso.', null=True),
        ),
    ]
