# Generated by Django 6.0.4 on 2026-07-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0003_examen_fecha_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='campo_estudio_habilitado',
            field=models.BooleanField(default=False, help_text='Si está activo, el docente puede publicar temas de estudio con IA y los estudiantes inscritos pueden verlos y preguntar sobre ellos.'),
        ),
    ]
