# Generated by Django 6.0.4 on 2026-07-29 20:16

from django.db import migrations, models


# Deja exentos a los cursos que ya existían antes de este cambio: solo los
# cursos creados de ahora en adelante (default=False del campo) piden el PDF
# del plan de aula.
def _marcar_cursos_existentes_como_completos(apps, schema_editor):
    Curso = apps.get_model('examenes', 'Curso')
    Curso.objects.update(plan_aula_cargado=True)


def _revertir_no_hace_nada(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0004_curso_campo_estudio_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='plan_aula_cargado',
            field=models.BooleanField(default=False, help_text='Indica si el docente ya subió el PDF del plan de aula y se generaron los objetivos iniciales del curso.'),
        ),
        migrations.RunPython(_marcar_cursos_existentes_como_completos, _revertir_no_hace_nada),
    ]
