# Generated by Django 6.0.4 on 2026-07-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0005_curso_plan_aula_cargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='peso_practica',
            field=models.FloatField(default=0, help_text='Porcentaje (0-100) que aporta la parte práctica (laboratorio vinculado) a la nota final. 0 = examen solo de teoría.'),
        ),
    ]
