# Generated by Django 6.0.4 on 2026-07-12 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examenes', '0002_objetivocurso_examen_objetivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('instrucciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorios', to='examenes.curso')),
            ],
            options={
                'db_table': 'laboratorios',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('lenguaje', models.CharField(choices=[('python', 'Python'), ('sql', 'SQL')], default='python', max_length=10)),
                ('codigo_inicial', models.TextField(blank=True, default='')),
                ('setup_sql', models.TextField(blank=True, default='', help_text='Solo para lenguaje=sql: DDL/DML para crear y poblar las tablas antes de la consulta del estudiante.')),
                ('criterios_ia', models.TextField(blank=True, default='', help_text='Instrucciones para evaluación por IA cuando no basta un test exacto (calidad, buenas prácticas).')),
                ('puntos', models.PositiveIntegerField(default=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='laboratorios.laboratorio')),
            ],
            options={
                'db_table': 'preguntas_codigo',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CasoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.TextField(blank=True, default='', help_text='stdin para Python. No aplica a SQL.')),
                ('salida_esperada', models.TextField(help_text='Salida exacta esperada: stdout en Python, resultado serializado en SQL.')),
                ('es_publico', models.BooleanField(default=False, help_text='Si True, el estudiante lo ve como ejemplo. Si False, es oculto y solo se usa para calificar.')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_test', to='laboratorios.preguntacodigo')),
            ],
            options={
                'db_table': 'casos_test',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
