# Generated by Django 6.0.4 on 2026-07-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntacodigo',
            name='lenguaje',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('sql', 'SQL')], default='python', max_length=10),
        ),
    ]
