# Generated by Django 6.0.4 on 2026-07-13 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0002_alter_preguntacodigo_lenguaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, help_text='Fecha límite para envíos calificados. Vacío = sin límite. No afecta "Ejecutar" (pruebas contra casos públicos).', null=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='max_intentos',
            field=models.PositiveIntegerField(default=0, help_text='Envíos calificados permitidos por pregunta. 0 = ilimitado.'),
        ),
        migrations.CreateModel(
            name='EntregaCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('resultados', models.JSONField(blank=True, default=list)),
                ('casos_pasados', models.PositiveIntegerField(default=0)),
                ('casos_totales', models.PositiveIntegerField(default=0)),
                ('puntaje', models.FloatField(default=0.0, help_text='0-100, = casos_pasados/casos_totales * 100')),
                ('intento', models.PositiveIntegerField(default=1)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_codigo', to=settings.AUTH_USER_MODEL)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='laboratorios.preguntacodigo')),
            ],
            options={
                'db_table': 'entregas_codigo',
                'ordering': ['-enviado_en'],
            },
        ),
    ]
