# Generated by Django 6.0.4 on 2026-07-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0004_generalizar_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='puntaje',
            field=models.FloatField(default=0.0, help_text='0-100. Código: casos_pasados/casos_totales * 100. Respuesta abierta: puntaje de la IA.'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='criterios_ia',
            field=models.TextField(blank=True, default='', help_text='Si tipo=respuesta_libre: rúbrica obligatoria que la IA usa para calificar. Si tipo=codigo: instrucciones opcionales para evaluación cualitativa adicional.'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='lenguaje',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('sql', 'SQL')], default='python', help_text='Solo aplica si tipo=codigo.', max_length=10),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='setup_sql',
            field=models.TextField(blank=True, default='', help_text='Solo para tipo=codigo y lenguaje=sql: DDL/DML para crear y poblar las tablas antes de la consulta del estudiante.'),
        ),
    ]
