# Generated by Django 6.0.4 on 2026-07-29 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0006_examen_peso_practica'),
        ('laboratorios', '0005_alter_entrega_puntaje_alter_pregunta_criterios_ia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='examen',
            field=models.ForeignKey(blank=True, help_text='Si está definido, este laboratorio es la parte práctica de este examen.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laboratorio_practica', to='examenes.examen'),
        ),
    ]
