# Generated by Django 6.0.4 on 2026-08-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0006_laboratorio_examen'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='imagen_respuesta',
            field=models.ImageField(blank=True, help_text='Foto de la solución manuscrita. Solo aplica si pregunta.tipo=problema_visual.', null=True, upload_to='problemas_visuales/respuestas/'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='imagen_enunciado',
            field=models.ImageField(blank=True, help_text='Diagrama generado por IA. Solo aplica si tipo=problema_visual.', null=True, upload_to='problemas_visuales/enunciados/'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='respuesta',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='criterios_ia',
            field=models.TextField(blank=True, default='', help_text='Si tipo=respuesta_libre o problema_visual: rúbrica obligatoria que la IA usa para calificar. Si tipo=codigo: instrucciones opcionales para evaluación cualitativa adicional.'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('codigo', 'Código'), ('respuesta_libre', 'Respuesta abierta'), ('problema_visual', 'Problema con imagen')], default='codigo', max_length=20),
        ),
    ]
