# Generated by Django 6.0.4 on 2026-08-09 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0007_entrega_imagen_respuesta_pregunta_imagen_enunciado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='imagen_respuesta',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='imagen_enunciado',
        ),
        migrations.AddField(
            model_name='entrega',
            name='opcion_seleccionada',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Índice (0-3) de la opción elegida. Solo aplica si pregunta.tipo=problema_visual.', null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='imagen_referencia',
            field=models.ImageField(blank=True, help_text='Imagen que el docente sube como guía/ejemplo. Opcional, solo contexto — no la procesa ninguna IA. Solo aplica si tipo=problema_visual.', null=True, upload_to='problemas_visuales/referencias/'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='criterios_ia',
            field=models.TextField(blank=True, default='', help_text='Si tipo=respuesta_libre: rúbrica obligatoria que la IA usa para calificar. Si tipo=codigo: instrucciones opcionales para evaluación cualitativa adicional. No aplica a tipo=problema_visual (calificación por opción múltiple, no por IA).'),
        ),
        migrations.CreateModel(
            name='VarianteProblemaVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='problemas_visuales/variantes/')),
                ('opciones', models.JSONField(help_text='Lista de 4 textos de opción, ej. ["...", "...", "...", "..."].')),
                ('respuesta_correcta', models.PositiveSmallIntegerField(help_text='Índice (0-3) de la opción correcta en "opciones".')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='laboratorios.pregunta')),
            ],
            options={
                'db_table': 'variantes_problema_visual',
            },
        ),
        migrations.CreateModel(
            name='AsignacionVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='laboratorios.pregunta')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorios.varianteproblemavisual')),
            ],
            options={
                'db_table': 'asignaciones_variante_problema_visual',
                'unique_together': {('pregunta', 'estudiante')},
            },
        ),
    ]
