# Generated by Django 6.0.4 on 2026-08-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0008_remove_entrega_imagen_respuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='audio_respuesta',
            field=models.FileField(blank=True, help_text='Grabación del estudiante. Solo aplica si pregunta.tipo=pronunciacion.', null=True, upload_to='pronunciacion/respuestas/'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='audio_referencia',
            field=models.FileField(blank=True, help_text='Audio de la pronunciación correcta, generado con Edge TTS. Solo aplica si tipo=pronunciacion.', null=True, upload_to='pronunciacion/referencias/'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='texto_pronunciar',
            field=models.CharField(blank=True, default='', help_text='Palabra o frase a pronunciar. Solo aplica si tipo=pronunciacion.', max_length=300),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('codigo', 'Código'), ('respuesta_libre', 'Respuesta abierta'), ('problema_visual', 'Problema con imagen'), ('pronunciacion', 'Pronunciación')], default='codigo', max_length=20),
        ),
    ]
