# Generated by Django 6.0.4 on 2026-08-24 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0006_examen_peso_practica'),
        ('laboratorios', '0009_entrega_audio_respuesta_pregunta_audio_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='objetivo',
            field=models.ForeignKey(blank=True, help_text='Objetivo del curso que evalúa esta pregunta, si se generó/asoció a partir de uno.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_laboratorio', to='examenes.objetivocurso'),
        ),
    ]
