# Generated by Django 6.0.4 on 2026-07-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='nota_practica',
            field=models.FloatField(blank=True, help_text='Nota (1.0-5.0) de la parte práctica (laboratorio vinculado), calculada al finalizarla. Null si el examen no tiene práctica o aún no se ha finalizado.', null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='nota_teoria',
            field=models.FloatField(blank=True, help_text='Snapshot de la nota (1.0-5.0) obtenida solo en la parte de teoría, antes de combinar con la práctica.', null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='puntaje_practica',
            field=models.FloatField(blank=True, help_text='Puntaje (0-100) de la parte práctica, promedio del mejor intento por pregunta del laboratorio vinculado.', null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='nota',
            field=models.FloatField(default=1.0, help_text='Calificación final en escala 1.0 a 5.0. Si el examen tiene práctica vinculada, es la combinación ponderada de nota_teoria y nota_practica; si no, es igual a nota_teoria.'),
        ),
    ]
