# Generated by Django 6.0.4 on 2026-07-24 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examenes', '0004_curso_campo_estudio_habilitado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas_estudio', to='examenes.curso')),
            ],
            options={
                'db_table': 'temas_estudio',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MensajeTemaEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('ia', 'IA')], max_length=20)),
                ('contenido', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_campo_estudio', to=settings.AUTH_USER_MODEL)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='campo_estudio.temaestudio')),
            ],
            options={
                'db_table': 'mensajes_tema_estudio',
                'ordering': ['creado_en'],
                'indexes': [models.Index(fields=['tema', 'estudiante', 'creado_en'], name='mensajes_te_tema_id_73b761_idx')],
            },
        ),
    ]
